version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Fprint
        - (io.Writer).Write
        - (*os.File).Close

run:
  timeout: 5m
